name: 'flights_dbt'
version: '1.0'
profile: 'flights_dbt'

models:
  flights_dbt:
    staging:
      +materialized: view  

vars:
  start_date: '2019-01-01'
  end_date: '2020-01-01'
  sample_size: 100000   
