apiVersion: 1

serviceAccounts:
  - name: demo-sa
    role: Admin
    tokens:
      - name: demo-token
        # Das ist das Geheimnis: Wir legen den Token im Voraus fest!
        # Er muss genau 32 Zeichen lang sein (ohne das glsa_ Präfix)
        token: glsa_mleProjectDemoTokenSecretKey12345_AbCdEfG
